### ISSUE TITLE
Long option --colors causes unhandled exception

### ISSUE THREAD

**Issue by hacxman** [c-blake/lc#4]
Hi, I've tried --colors without reading docs beforehand and I've got this:

```bash
$ ./lc --colors
/home/hexo/local/lc/lc.nim(970) lc
/home/hexo/local/lc/lc.nim(788) fin
/tmp/nimble_1865576/githubcom_cblakecligengit_1.2.0/cligen/humanUt.nim(92) textAttrRegisterAliases
/usr/lib/nim/system/fatal.nim(39) sysFatal
Error: unhandled exception: index 1 not in 0 .. 0 [IndexError]
```

another long opt --yolo seems to be handled just fine, look:

```bash
$ ./lc --yolo
Unknown long option: "yolo"

Maybe you meant one of:
        color help colors

Run with --help for full usage.
```

**Comment by c-blake** [comment]
First, apologies for the long delay responding to this.  You posted it at a time when I was getting literally dozens of github notifies per day and I overlooked yours.

Second, your diagnosis is slightly off track since --colors is a real option expecting an argument.  The empty string/seq is simply an invalid such argument.

Third, thanks - this was a real bug/fragility, but more in `cligen` than here.  I just pushed a fix.  There could easily be similar such lurking bugs and I'm happy to fix them.
